# Generated by Django 4.2.16 on 2024-10-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
