# Generated by Django 5.1.1 on 2024-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
